#服务器端口
server:
  port: 8107


#数据源配置
spring:
  datasource:
    dynamic:
      datasource:
        master:
          username: ${blade.datasource.dev.username}
          password: ${blade.datasource.dev.password}
          url: ${blade.datasource.dev.url}
          driver-class-name: oracle.jdbc.driver.OracleDriver
        smsman:
          username: ${smsman.datasource.dev.username}
          password: ${smsman.datasource.dev.password}
          url: ${smsman.datasource.dev.url}
          driver-class-name: oracle.jdbc.driver.OracleDriver
      p6spy: true
  redis:
    database: 5

zwx:
  command:
    host: 192.168.3.231
    port: 7001
    content: UpdateAllConfig

mybatis-plus:
  type-enums-package: org.springblade.system.enums
  global-config:
    sql-parser-cache: true
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.EnumTypeHandler


